spring.application.name=api-gateway
server.port=8080

# product-service configuration
spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/product/**

# order-service configuration
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/order/**

# inventory-service configuration
spring.cloud.gateway.server.webflux.routes[2].id=inventory-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/inventory/**

# service-discovery configuration
spring.cloud.gateway.server.webflux.routes[3].id=service-discovery
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/eureka/web
spring.cloud.gateway.server.webflux.routes[3].filters[0]=SetPath=/

spring.cloud.gateway.server.webflux.routes[4].id=service-discovery-static
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/eureka/**

#Zipkin setup
# Management + Tracing Settings
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# Zipkin Exporter Configuration (Note the new path: management.zipkin.tracing.endpoint)
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Logging pattern to see Trace/Span IDs in the console (Optional but recommended)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]