spring.application.name=service-discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
server.port=8761

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Enable tracing
# Management + Tracing Settings
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# Zipkin Exporter Configuration (Note the new path: management.zipkin.tracing.endpoint)
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Logging pattern to see Trace/Span IDs in the console (Optional but recommended)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]